### ISSUE TITLE
Unable to browse the secrets under the path pki/ from vault UI

### ISSUE THREAD

**Issue by gladjoe** [Venafi/vault-pki-monitor-venafi#84] opened 2022-04-29 02:22 UTC
**PROBLEM SUMMARY**
We are using the vault-pki-monitor-venafi plugin with our TPP server. we are able to successfully issue/monitor certs from Vault.
But, we are not able to view the certificate from Vault UI under secrets. we can view the secrets path, but cant click.

**STEPS TO REPRODUCE**
1. Configure the vault-pki-monitor-venafi plugin as per the documentation. Follow all the steps till step 14.
2. Generate a certificate by writing to the Vault CA and the Venafi role.
    # vault write pki/issue/venafi-role common_name="test.allowed.org" alt_names="test-1.allowed.org,test-2.allowed.org"
3. Certificate successfully issued.
4. Access the Vault UI $VAULT_ADDR/ui/vault/secrets
5. the "pki/" wont be accessible

**EXPECTED RESULTS**
Should be able to browse through the certicates under "pki/"

**ACTUAL RESULTS**
There is no error. but "pki/" is not accessible from the UI

**ENVIRONMENT DETAILS**
TPP server hosted on VM Server
Vault is running as Docker container on Laptop

**Comment by tr1ck3r** [comment] 2022-04-29 03:03
@gladjoe it has been a couple years since we inquired but at the time HashiCorp informed us that external plugins like ours aren't fully supported by the Vault web UI.  We will follow up with our contacts to see if anything has changed.  Will change to enhancement since we know it was not possible to support the Vault web UI at the time this secrets engine was developed.

**Comment by tr1ck3r** [comment] 2022-04-29 15:27
@gladjoe I received confirmation from HashiCorp that, unfortunately, external plugins are still not supported by the Vault web UI.  They're interested in associating you and your organization with that enhancement request so would you please send your contact information to opensource@venafi.com when you have a chance?

**Comment by gladjoe** [comment] 2022-05-02 00:41
@tr1ck3r Thanks for your response

**Comment by luispresuelVenafi** [comment] 2022-10-06 08:58
I'm closing this issue as it's been confirmed it doesn't depend on us.

**Closed by luispresuelVenafi** 2022-10-06 08:58 UTC
Labels: enhancement
